desc staffs;

ALTER TABLE STAFFS MODIFY TEAM_NAME NULL;
ALTER TABLE STAFFS MODIFY S_NAME NULL;
ALTER TABLE STAFFS MODIFY S_POSITION NULL;
ALTER TABLE STAFFS MODIFY S_CODE NULL;

select * from staffs;


INSERT INTO CONTRACTS VALUES(




);
