DESC STAFFS;

--STAFFS 제약조건 설정
--TASK 제외 NOT NULL
ALTER TABLE STAFFS MODIFY TEAM_NAME NOT NULL;
ALTER TABLE STAFFS MODIFY S_NAME NOT NULL;
ALTER TABLE STAFFS MODIFY S_POSITION NOT NULL;

--스태프 코드를 위한 시퀀스 생성
CREATE SEQUENCE STAFFS_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999
    MINVALUE 1
    NOCYCLE
    NOCACHE;
-- 시퀀스 사용 준비 끝!
SELECT STAFFS_SEQ.NEXTVAL FROM DUAL; 
SELECT STAFFS_SEQ.CURRVAL FROM DUAL;

--STAFFS 테이블에 S_CODE 컬럼 추가
ALTER TABLE STAFFS ADD (S_CODE NUMBER(3));

--기 입력된 테이더 수정(S_CODE 추가)
UPDATE STAFFS
SET S_CODE = STAFFS_SEQ.NEXTVAL
WHERE TEAM_NAME = '흥국생명 핑크스파이더스';

ALTER SEQUENCE STAFFS_SEQ MINVALUE 0;

SELECT STAFFS_SEQ.CURRVAL FROM DUAL;
ALTER SEQUENCE STAFFS_SEQ INCREMENT BY 1;
SELECT STAFFS_SEQ.NEXTVAL FROM DUAL;

COMMIT;

UPDATE STAFFS
SET S_CODE = 1
WHERE S_NAME = '마르첼로 아본단자';

UPDATE STAFFS
SET S_CODE = STAFFS_SEQ.NEXTVAL
WHERE S_NAME IN('최지완', '이택규', '이주현', '김예솔');

UPDATE STAFFS
SET S_CODE = STAFFS_SEQ.NEXTVAL
WHERE TEAM_NAME = 'GS칼텍스 KIXX' ;

SELECT * FROM STAFFS;
COMMIT;

--S_CODE 컬럼 PK지정
ALTER TABLE STAFFS ADD PRIMARY KEY (S_CODE);

SELECT * FROM STAFFS WHERE TEAM_NAME = '흥국생명 핑크스파이더스';

INSERT INTO STAFFS(TEAM_NAME, S_NAME, S_POSITION, TASK)
VALUES('흥국생명 핑크스파이더스', '배재욱', 'CO', '훈련관리');

ALTER TABLE STAFFS ADD (S_CODE NUMBER(10));
ALTER TABLE STAFFS DROP COLUMN S_CODE;
SELECT * FROM STAFFS;

UPDATE STAFFS
SET TEAM_NAME = 'GS칼텍스 KIXX',
    S_NAME = '테스트',
    S_POSITION = 'DIR',
    TASK = '총괄 관리자'
WHERE S_CODE = 6;

DELETE FROM STAFFS WHERE S_CODE = 10;

SELECT * FROM STAFFS;
--insert시 에러가 나서 not null 해제
ALTER TABLE STAFFS MODIFY TEAM_NAME NULL;
ALTER TABLE STAFFS MODIFY S_NAME NULL;
ALTER TABLE STAFFS MODIFY S_POSITION NULL;
ALTER TABLE STAFFS MODIFY S_CODE NULL;

--FK 무결성 침해하여 해제
ALTER TABLE STAFFS DROP CONSTRAINT STAFF_NO_FK;

COMMIT;

CREATE TABLE TRANSFER (
    


);

